name: Unit Test and Coverage

on:
  push:
  pull_request:

jobs:
  unit-test-coverage:
    name: Run unit test and coverage
    uses: nasa/cFS/.github/workflows/unit-test-coverage.yml@main
    with:
      max-missed-branches: 3
      max-missed-lines: 5
